'use strict';
/* ============================================================
   Pixel Peaks â€” worlds & levels
   Level def: {name, w, rows:[13 strings = map rows 2..14],
               pits:[[col,len]], ice:[[col,len]], cave:true}
   Ground (rows 15,16) & cave ceilings are generated by expand().
   Legend: # solid  I ice  - one-way  ^ spikes  S spring
           o coin   G gem  P spawn   F flag    C checkpoint
           W walker V flyer M moverH  N moverV
   Max jump â‰ˆ 2.1 tiles high / 3 tiles across (4 sprinting).
   ============================================================ */
const THEMES={
  grass:{sky:['#3f96d8','#7fc3ea','#d8f4fc'],sun:{c:'#fff2ae',g:'rgba(255,240,170,0.35)',x:392,y:42,r:13},stars:0,
    far:'#4d9b8e',near:'#2f7a5e',outline:'#241812',
    cap:'#52b84a',capHi:'#93e06a',capLo:'#3a8f38',body:'#8a5a3b',hi:'#a97448',lo:'#5e3c22',
    wood:'#a9743f',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'hills',deco:'meadow',amb:null,lava:false},
  sand:{sky:['#e8933f','#f5c97e','#fdf0cd'],sun:{c:'#fff6d8',g:'rgba(255,235,180,0.4)',x:392,y:38,r:15},stars:0,
    far:'#cf9a4e',near:'#a86f34',outline:'#4a2f14',
    cap:'#eec768',capHi:'#fbe29a',capLo:'#c69a44',body:'#cf9c58',hi:'#e0b26e',lo:'#9a7038',
    wood:'#b5824a',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'dunes',deco:'desert',amb:null,lava:false},
  cave:{sky:['#120d2c','#1e1745','#2c2158'],sun:null,stars:2,
    far:'#241c4e',near:'#332866',outline:'#0d0a1e',
    cap:'#7c72a8',capHi:'#a297d4',capLo:'#5a5186',body:'#453d60',hi:'#575070',lo:'#2e2844',
    wood:'#6b5a8a',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'cave',deco:'crystal',amb:null,lava:false},
  snow:{sky:['#6fa3d4','#a9cce8','#e8f4fb'],sun:{c:'#ffffff',g:'rgba(255,255,255,0.3)',x:392,y:40,r:11},stars:0,
    far:'#8fb4d8',near:'#5f88b4',outline:'#2c3c55',
    cap:'#f4faff',capHi:'#ffffff',capLo:'#c8dcf0',body:'#7e93b8',hi:'#94a9cc',lo:'#5c7098',
    wood:'#8fa3c4',iceCap:'#d8f4ff',iceBody:'#a5d8ef',iceDark:'#78b4d4',
    bg:'peaks',deco:'snow',amb:'snow',lava:false},
  sunset:{sky:['#2c1a4a','#c8556a','#ffa050'],sun:{c:'#ffd9a0',g:'rgba(255,170,90,0.35)',x:240,y:128,r:24},stars:0,
    far:'#5c3060',near:'#3c2050',outline:'#1a0e22',
    cap:'#c88a5a',capHi:'#e8b284',capLo:'#96603a',body:'#96634a',hi:'#a87858',lo:'#6a4432',
    wood:'#b5804a',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'mesa',deco:'ruin',amb:null,lava:false},
  sky:{sky:['#5aa8e8','#93ccf2','#e8f6fc'],sun:{c:'#fff6c8',g:'rgba(255,244,190,0.4)',x:66,y:40,r:14},stars:0,
    far:'#7fb8d8',near:'#a8d4e8',outline:'#3a5a78',
    cap:'#e8d890',capHi:'#fbebae',capLo:'#c8b460',body:'#b8c4d8',hi:'#ccd6e4',lo:'#8a98b0',
    wood:'#c8b478',iceCap:'#d8f4ff',iceBody:'#a5d8ef',iceDark:'#78b4d4',
    bg:'cloudsea',deco:'cloud',amb:null,lava:false},
  lava:{sky:['#180c12','#3d1420','#5c2028'],sun:null,stars:1,
    far:'#331a28',near:'#47202e',outline:'#0d060a',
    cap:'#8a6a78',capHi:'#a8889a',capLo:'#6a4c5c',body:'#4c3a52',hi:'#5e4a64',lo:'#342640',
    wood:'#5d4a63',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'volcano',deco:'ember',amb:'embers',lava:true},
  night:{sky:['#070716','#141238','#282052'],sun:{c:'#e8ecf8',g:'rgba(200,215,255,0.22)',x:396,y:40,r:14,moon:true},stars:3,
    far:'#1c1848',near:'#2a2458',outline:'#05050e',
    cap:'#5a6ab0',capHi:'#8896d8',capLo:'#425090',body:'#3a3860',hi:'#4a4878',lo:'#282648',
    wood:'#565a8a',iceCap:'#cfeeff',iceBody:'#9fd0ea',iceDark:'#6fa8c8',
    bg:'peaks',deco:'glow',amb:'fireflies',lava:false}
};
const _='..........';
const E=n=>_.repeat(n);
const H=n=>'#'.repeat(n);
/* ---------- authoring toolkit ----------
   Physics envelope (PCFG in main.js): a standing-start jump gains â‰ˆ2 tiles and
   crosses â‰ˆ3 (sprinting); springs reach â‰ˆ8 tiles; movers sweep Â±3 tiles.
   Every segment below is built inside that envelope, and test.js re-verifies
   each level with a real-physics BFS (flag, movers, boxes, coverage).
   Enemies all have a job: walkers hold the run-ups before hazards, flyers
   hover on the jump arcs over every crossing, turrets own tower tops and the
   choke points between hazards. */
function putS(r,y,x,s){r[y]=r[y].slice(0,x)+s+r[y].slice(x+s.length);}
function build(W,fn){const r=[];for(let i=0;i<13;i++)r.push('.'.repeat(W));fn(r);return r;}
function pk(r,x,h){for(let i=0;i<h;i++)putS(r,12-i,x,'#');}
function pt(r,y,x,len){putS(r,y,x,H(len));}
function ow(r,y,x,len){putS(r,y,x,'-'.repeat(len));}
function cn(r,y,x,n){putS(r,y,x,'o'.repeat(n));}
function spk(r,x,n){putS(r,12,x,'^'.repeat(n));}
function at(r,x,ch){putS(r,12,x,ch);}
function up(r,y,x,ch){putS(r,y,x,ch);}
function stU(r,x,n){for(let i=0;i<n;i++)pk(r,x+i,i+1);}
function stD(r,x,n){for(let i=0;i<n;i++)pk(r,x+i,n-i);}
function rng32(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
/* composite gauntlet segments — each is a self-contained challenge where every
   enemy has a job (walkers hold run-ups, flyers guard jump arcs, turrets own
   choke points). Each returns its width in tiles and self-varies via c.R() so
   no two appearances look alike. Kinds: 'ground' running hazards, 'vertical'
   climbs, 'air' gap crossings. No side-to-side platforms over gap jumps. */
const SEG={
  coins(c,x){cn(c.r,c.R()<0.5?9:10,x+2,4);if(c.R()<c.hot)at(c.r,x+9,'W');if(c.ice)c.I(x+1,10);return 12;},
  walk(c,x){at(c.r,x+1,'W');if(c.R()<0.5)pk(c.r,x+6,1);cn(c.r,9,x+6,3);if(c.R()<c.hot)at(c.r,x+11,'W');if(c.ice)c.I(x+1,13);return 15;},
  spike(c,x){spk(c.r,x+2,c.R()<c.hot-0.1?3:2);at(c.r,x+7,'W');cn(c.r,9,x+10,3);if(c.ice)c.I(x+1,13);return 15;},
  pillar(c,x){const h2=c.li>5&&c.R()<0.5?3:2;const hs=[2,h2,1+(c.R()<0.5?1:0)];pk(c.r,x+2,hs[0]);pk(c.r,x+5,hs[1]);pk(c.r,x+8,hs[2]);cn(c.r,12-hs[0],x+3,1);cn(c.r,11-hs[1],x+6,2);at(c.r,x+12,'W');return 17;},
  dipRun(c,x){const n=2+((c.R()*2)|0),st=5+((c.R()*2)|0);for(let i=0;i<n;i++){const pw=1+((c.R()*2)|0);c.P(x+2+i*st,pw);cn(c.r,10,x+2+i*st,pw);}if(c.ice)c.I(x+1,st*n+3);return st*n+6;},
  hopScotch(c,x){const n=3+((c.R()*2)|0);for(let i=0;i<n;i++){const h=i===0?1:(c.R()<0.4?2:1);pk(c.r,x+2+i*3,h);cn(c.r,11-h,x+2+i*3,1);if(i<n-1)spk(c.r,x+3+i*3,1);}up(c.r,8,x+2+((n/2)|0)*3,'V');return 3*n+5;},
  springVault(c,x){at(c.r,x+2,'S');cn(c.r,5,x+4,3);pk(c.r,x+6,2);up(c.r,10,x+6,'G');at(c.r,x+11,'W');return 15;},
  corridor(c,x){const len=10+((c.R()*5)|0);pt(c.r,10,x+1,len);at(c.r,x+3,'W');cn(c.r,11,x+6,3);if(c.R()<c.hot)at(c.r,x+len-3,'W');return len+2;},
  islands(c,x){const n=3+((c.R()*2)|0);c.P(x+1,3*n);for(let i=0;i<n;i++){const y=i%2?11:12;putS(c.r,y,x+2+i*3,'#');cn(c.r,y-2,x+2+i*3,1);}up(c.r,8,x+2+((n/2)|0)*3,'V');return 3*n+4;},
  stairGap(c,x){const n=3+(c.li>6?1:0),g=2+(c.R()<0.5?1:0);stU(c.r,x,n);c.P(x+n,g);stD(c.r,x+n+g,n);cn(c.r,13-n,x+n+((g/2)|0),1);return 2*n+g+2;},
  turretAlley(c,x){pk(c.r,x+2,1);at(c.r,x+4,'X');spk(c.r,x+8,c.R()<c.hot?3:2);cn(c.r,9,x+11,3);return 16;},
  elevator(c,x){up(c.r,9,x+2,'N');pt(c.r,6,x+6,6);cn(c.r,5,x+7,3);up(c.r,4,x+8,'G');return 14;},
  elevatorDrop(c,x){up(c.r,9,x+2,'N');pt(c.r,7,x+5,4);cn(c.r,6,x+6,2);up(c.r,5,x+6,'G');ow(c.r,11,x+10,3);return 15;},
  shelves(c,x){const st=c.li>5?3:2;c.P(x,4*st+2);for(let i=0;i<st;i++){ow(c.r,12-2*i,x+4*i,4);cn(c.r,11-2*i,x+4*i+1,2);}up(c.r,Math.max(2,8-2*st),x+4*(st-1)+1,'V');return 4*st+4;},
  flyerGauntlet(c,x){up(c.r,8,x+3,'V');up(c.r,10,x+8,'V');cn(c.r,9,x+5,3);cn(c.r,9,x+9,2);if(c.ice)c.I(x+1,12);return 14;},
  iceBridge(c,x){c.I(x+1,15);let w=4+((c.R()*2)|0);c.P(x+w,2);cn(c.r,10,x+w,2);w+=6+((c.R()*2)|0);c.P(x+w,2);cn(c.r,10,x+w,2);at(c.r,x+w-3,'W');return w+6;},
  tower(c,x){const st=c.li>7?3:2;const len=8+2*st;pk(c.r,x+1,2);for(let i=0;i<st;i++)pt(c.r,10-2*i,x+3+2*i,len-2*i);cn(c.r,9-2*(st-1),x+7+2*(st-1),3);up(c.r,9-2*(st-1)-1,x+9+2*(st-1),'G');return len+6;},
  bridgeRun(c,x){const n=3+((c.R()*2)|0);let w=0;for(let i=0;i<n;i++){const pw=3+((c.R()*2)|0);ow(c.r,11-(i%2),x+2+w,pw);cn(c.r,9-(i%2),x+3+w,2);w+=pw+2+((c.R()*2)|0);}c.P(x+1,w-1);up(c.r,8,x+4+((n/2)|0)*5,'V');return w+4;},
  pitMaze(c,x){const n=3+((c.R()*2)|0);c.P(x+1,3*n);for(let i=0;i<n;i++){putS(c.r,i%2?11:12,x+2+i*3,'#');cn(c.r,(i%2?11:12)-2,x+2+i*3,1);}up(c.r,8,x+3+((n/2)|0)*3,'V');return 3*n+4;},
  gemLoft(c,x){at(c.r,x+2,'S');pt(c.r,6,x+7,4);cn(c.r,5,x+7,3);up(c.r,4,x+8,'G');up(c.r,8,x+12,'V');return 17;},
  /* ---- world-signature segments: one pair per world, so each world has
     patterns no other world ever uses ---- */
  hedgerow(c,x){pk(c.r,x+3,1+(c.R()<0.5?1:0));pk(c.r,x+10,1+(c.R()<0.5?1:0));cn(c.r,10,x+5,2);cn(c.r,9,x+7,1);at(c.r,x+6,'W');return 15;},
  orchard(c,x){for(let i=0;i<3;i++){const ty=8+((c.R()*3)|0),tw=3+((c.R()*2)|0);ow(c.r,ty,x+2+i*6,tw);cn(c.r,ty-1,x+3+i*6,2);}at(c.r,x+5,'W');if(c.R()<c.hot)at(c.r,x+13,'W');return 21;},
  duneDive(c,x){stU(c.r,x,3);c.P(x+3,2);stD(c.r,x+5,3);spk(c.r,x+9,2);cn(c.r,8,x+3,1);at(c.r,x+12,'W');return 15;},
  oasisVault(c,x){at(c.r,x+2,'S');spk(c.r,x+4,6);cn(c.r,7,x+6,3);at(c.r,x+12,'W');return 16;},
  stalagmite(c,x){pk(c.r,x+2,2);pk(c.r,x+5,1);pk(c.r,x+8,c.R()<0.5?1:2);spk(c.r,x+11,c.R()<c.hot?2:1);cn(c.r,9,x+2,1);cn(c.r,10,x+8,1);at(c.r,x+14,'W');return 17;},
  crystalClimb(c,x){ow(c.r,11,x+2,3);ow(c.r,9,x+6,3);ow(c.r,7,x+10,3);cn(c.r,6,x+11,2);up(c.r,6,x+13,'G');return 17;},
  snowdrift(c,x){stU(c.r,x,2);pt(c.r,10,x+2,6);stD(c.r,x+8,2);up(c.r,9,x+5,'W');cn(c.r,9,x+3,1);return 12;},
  mesaTops(c,x){let w=0;for(let i=0;i<3;i++){const mw=3+((c.R()*2)|0),mh=c.R()<0.5?1:0;pt(c.r,11,x+1+w,mw);if(mh)pt(c.r,12,x+1+w,mw);cn(c.r,10,x+2+w,1+((c.R()*2)|0));if(i<2){c.P(x+1+w+mw,3);w+=mw+3;}else w+=mw;}up(c.r,9,x+w-1,'V');return w+3;},
  ruinHalls(c,x){ow(c.r,11,x+2,8);spk(c.r,x+4,c.R()<c.hot?3:2);cn(c.r,10,x+3,3);cn(c.r,10,x+7,2);at(c.r,x+12,'W');return 15;},
  cloudHops(c,x){c.P(x+1,13);ow(c.r,12,x+2,3);ow(c.r,11,x+6,3);cn(c.r,10,x+7,2);cn(c.r,9,x+3,2);up(c.r,8,x+10,'V');return 16;},
  skyGarden(c,x){pt(c.r,11,x+1,4);up(c.r,10,x+2,'S');c.P(x+5,4);pt(c.r,8,x+9,4);cn(c.r,7,x+10,2);up(c.r,9,x+7,'V');return 15;},
  emberPits(c,x){let w=0;for(let i=0;i<3;i++){const g=3+((c.R()*2)|0);c.P(x+1+w,2);cn(c.r,10,x+1+w,2);w+=2+g;}at(c.r,x+2+w,'W');return w+5;},
  lavaGeysir(c,x){at(c.r,x+1,'S');c.P(x+3,4);pt(c.r,9,x+3,3);cn(c.r,7,x+4,2);cn(c.r,9,x+8,3);at(c.r,x+11,'W');return 16;},
  graveyard(c,x){const n=4+((c.R()*2)|0);let w=0;for(let i=0;i<n;i++){const ph=i===0?1:(c.R()<0.4?2:1),p=2+((c.R()*2)|0);putS(c.r,12-ph,x+1+w+p,'#');if(c.R()<0.4)cn(c.r,10-ph,x+1+w+p,1);w+=p;}c.P(x+1,w+3);up(c.r,9,x+3+((n/2)|0)*4,'V');return w+8;},
  moonlitRoofs(c,x){pk(c.r,x+1,1);c.P(x+2,2);pk(c.r,x+4,2);c.P(x+5,2);pk(c.r,x+7,3);cn(c.r,11,x+1,1);cn(c.r,10,x+4,1);cn(c.r,9,x+7,1);up(c.r,8,x+5,'V');return 11;},
  bouncyAlley(c,x){at(c.r,x+2,'S');at(c.r,x+8,'S');cn(c.r,6,x+3,2);cn(c.r,6,x+9,2);up(c.r,8,x+5,'V');spk(c.r,x+12,c.R()<c.hot?2:1);return 15;}
};
const KIND={coins:'ground',walk:'ground',spike:'ground',pillar:'ground',dipRun:'ground',
  hopScotch:'ground',springVault:'vertical',corridor:'ground',islands:'air',stairGap:'air',
  turretAlley:'ground',elevator:'vertical',elevatorDrop:'vertical',shelves:'vertical',
  flyerGauntlet:'ground',iceBridge:'ground',tower:'vertical',bridgeRun:'air',pitMaze:'air',gemLoft:'vertical',
  hedgerow:'ground',orchard:'ground',duneDive:'ground',oasisVault:'vertical',stalagmite:'ground',
  crystalClimb:'vertical',snowdrift:'ground',mesaTops:'air',ruinHalls:'ground',cloudHops:'air',
  skyGarden:'vertical',emberPits:'ground',lavaGeysir:'vertical',graveyard:'air',moonlitRoofs:'vertical',
  bouncyAlley:'ground'};
/* silhouette families — segments that *look* alike may not appear near each
   other, so a "2-high blocks + spikes" motif never shows up twice in a row */
const LOOK={coins:'run',walk:'run',corridor:'run',flyerGauntlet:'run',snowdrift:'run',orchard:'run',
  spike:'blk',pillar:'blk',stalagmite:'blk',hopScotch:'blk',turretAlley:'blk',hedgerow:'blk',
  ruinHalls:'blk',emberPits:'blk',duneDive:'blk',
  dipRun:'gap',iceBridge:'gap',bridgeRun:'gap',islands:'gap',pitMaze:'gap',graveyard:'gap',
  cloudHops:'gap',mesaTops:'gap',stairGap:'gap',
  springVault:'climb',elevator:'climb',elevatorDrop:'climb',shelves:'climb',tower:'climb',
  crystalClimb:'climb',skyGarden:'climb',lavaGeysir:'climb',moonlitRoofs:'climb',gemLoft:'climb',
  bouncyAlley:'climb',oasisVault:'climb'};
function poolFor(wi){
  const p=['coins','walk','spike','pillar','dipRun','hopScotch','springVault','corridor','islands','stairGap'];
  const add=(...t)=>{for(const q of t)if(!p.includes(q))p.push(q);};
  if(wi>=1)add('turretAlley','elevator');
  if(wi>=2)add('shelves','flyerGauntlet','elevatorDrop','bouncyAlley');
  if(wi>=4)add('tower','bridgeRun','pitMaze');
  if(wi>=6)add('gemLoft');
  // world-exclusive signature patterns — no two worlds share these
  const SIG=[['hedgerow','orchard'],['duneDive','oasisVault'],['stalagmite','crystalClimb'],
    ['snowdrift'],['mesaTops','ruinHalls'],['cloudHops','skyGarden'],
    ['emberPits','lavaGeysir'],['graveyard','moonlitRoofs']];
  add(...SIG[wi]);
  return p;
}
/* seeded composer: opener → chaptered gauntlet (ground run → vertical climbs →
   air crossings) → grand stair → flag. Each level shuffles its world pool with
   its own seed and rotates the start, so every level runs a distinct sequence
   of segment patterns; segments also self-vary on every single appearance. */
function mkLevel(W,seed,wi,li,ice){
  const R=rng32(seed),pits=[],spans=ice?[]:null;
  const r=build(W,()=>{});
  const c={r,P:(x,w)=>pits.push([x,w]),I:(x,w)=>{if(spans&&w>0)spans.push([x,w]);},R,wi,li,hot:0.2+li*0.06,ice};
  at(r,3,'P');cn(r,10,8,4);at(r,20,'W');
  // per-level palette: seeded shuffle of the world pool, rotated by level index
  const RP=rng32((seed^0x5bd1e995)>>>0);
  const pal=poolFor(wi).slice();
  for(let i=pal.length-1;i>0;i--){const j=(RP()*(i+1))|0;const t=pal[i];pal[i]=pal[j];pal[j]=t;}
  const ordered=pal.slice(li%pal.length).concat(pal.slice(0,li%pal.length));
  const used={};ordered.forEach(t=>used[t]=0);
  const cap=Math.max(2,Math.ceil((W-70)/16/pal.length));
  const inPit=x=>pits.some(p=>x>=p[0]&&x<p[0]+p[1]);
  const phaseOf=x=>x<W*0.35?'open':x<W*0.68?'mid':'end';
  const okK=(t,ph)=>ph==='open'?KIND[t]!=='air':ph==='mid'?KIND[t]!=='ground':KIND[t]!=='vertical';
  const recent=[],recentFam=[];   // anti-repeat: same segment within 4 picks,
                                  // same silhouette family within 3 picks
  const famOK=t=>!recentFam.includes(LOOK[t]);
  let x=26,bag=ordered.slice();
  while(x<W-40){
    const ph=phaseOf(x);
    let t=null;
    for(let tri=0;tri<50&&!t;tri++){
      if(!bag.length){bag=ordered.slice();
        for(let i=bag.length-1;i>0;i--){const j=(R()*(i+1))|0;const q=bag[i];bag[i]=bag[j];bag[j]=q;}}
      let ci=bag.findIndex(q=>okK(q,ph)&&!recent.includes(q)&&famOK(q)&&used[q]<cap);
      if(ci<0)ci=bag.findIndex(q=>okK(q,ph)&&!recent.includes(q)&&used[q]<cap);
      if(ci<0)ci=bag.findIndex(q=>okK(q,ph)&&famOK(q)&&used[q]<cap);
      if(ci<0)bag.length=0;else{t=bag[ci];bag.splice(ci,1);}
    }
    if(!t)t=ordered.find(q=>okK(q,ph)&&!recent.includes(q)&&famOK(q)&&used[q]<cap)
          ||ordered.find(q=>okK(q,ph)&&!recent.includes(q)&&used[q]<cap)
          ||ordered.find(q=>okK(q,ph)&&famOK(q))
          ||ordered.find(q=>okK(q,ph))
          ||ordered[(R()*ordered.length)|0];
    used[t]++;recent.push(t);if(recent.length>4)recent.shift();
    recentFam.push(LOOK[t]);if(recentFam.length>3)recentFam.shift();
    x+=SEG[t](c,x)+1+((R()*3)|0);
  }
  // density pass: nothing pointless — any flat, featureless stretch of 10+
  // tiles gets intentional filler (a coin line to run, or a patrolling walker)
  let fx=30;
  while(fx<W-48){
    const empty=q=>q<W&&!inPit(q)&&r[12][q]==='.'&&r[11][q]==='.'&&r[10][q]==='.'&&r[9][q]==='.'&&r[8][q]==='.';
    if(empty(fx)){
      let e2=fx;while(e2<W-48&&empty(e2))e2++;
      if(e2-fx>=10){const mid=fx+((e2-fx)/2|0);
        if(R()<0.6)cn(r,9,mid-1,3);else at(r,mid,'W');}
      fx=e2;
    }else fx++;
  }
  // two mid-level checkpoints on clear, solid ground — long levels need them
  const placeC=t=>{
    const tx=Math.round(W*t);
    for(let d=0;d<80;d++){
      for(const s of d===0?[tx]:[tx-d,tx+d]){
        if(s>18&&s<W-30&&!inPit(s)&&r[12][s]==='.'&&r[11][s]==='.'&&r[10][s]==='.'){at(r,s,'C');return;}
      }
    }
  };
  placeC(0.34);placeC(0.67);
  const n=Math.min(7,5+(wi>3?1:0)+(wi>6?1:0));
  stU(r,x,n);at(r,Math.min(W-6,x+n+4),'F');
  const def={w:W,pits,rows:r};
  if(spans)def.ice=spans;
  return def;
}
function mkLvl(wi,li,nm,W,extra){return Object.assign({name:nm},extra||{},mkLevel(Math.round(W*2.75),wi*131+li*17+5,wi,li,!!(extra&&extra.ice)));}

const WORLDS=[
/* ============ WORLD 1 Â· EMERALD MEADOWS ============ */
{name:'Emerald Meadows',theme:'grass',lvls:[
 ['First Steps',320],['Coin Steps',350],['Spring Song',360],['Meadow Dash',400],
 ['Walker Woods',330],['Pillar Hop',350],['Turret Rise',360],['The Long Glide',380],
 ['Spike Alley',350],['Springs & Bats',370],['Gauntlet Prairie',400],['Meadow Citadel',440]
].map((n,li)=>mkLvl(0,li,n[0],n[1]))},
/* ============ WORLD 2 Â· SUNSCORCH DUNES ============ */
{name:'Sunscorch Dunes',theme:'sand',lvls:[
 ['Dune Trot',340],['Quicksand Pits',360],['Pyramid Climb',380],['Mirage',400],
 ['Oasis Run',340],['Scarab Swarm',360],['Ziggurat Ascent',380],['Sunken Tomb',400],
 ['Mirage Market',360],['Dust Devil Dash',390],['Sphinx Steps',410],['Dune Citadel',440]
].map((n,li)=>mkLvl(1,li,n[0],n[1]))},
/* ============ WORLD 3 Â· CRYSTAL CAVE ============ */
{name:'Crystal Cave',theme:'cave',lvls:[
 ['Glow Wade',340],['Shard Steps',360],['Deep Drop',380],['Crystal Heart',420],
 ['Fungus Hollow',340],['Elevator Shaft',360],['Gem Vault',380],['Stalactite Sprint',400],
 ['Underground Lake',360],['Crystal Caverns',390],['Echo Gauntlet',410],['Cave Citadel',440]
].map((n,li)=>mkLvl(2,li,n[0],n[1],{cave:true}))},
/* ============ WORLD 4 Â· FROST PEAKS (ice is slippery) ============ */
{name:'Frost Peaks',theme:'snow',lvls:[
 ['Powder Trail',340],['Slick Slopes',370],['Glacier Gap',420],['Blizzard Walk',450],
 ['Frozen Falls',350],['Icebound Bridge',380],['Snowdrift Sprint',400],['Aurora Fields',370],
 ['Whiteout',400],['Crevasse Cross',420],['Polar Gauntlet',430],['Summit Approach',450]
].map((n,li)=>mkLvl(3,li,n[0],n[1],{ice:true}))},
/* ============ WORLD 5 Â· SUNSET RUINS ============ */
{name:'Sunset Ruins',theme:'sunset',lvls:[
 ['Old Pillars',340],['Broken Bridge',370],['Mover Maze',390],['Ruin Runner',420],
 ['Crumbled Court',340],['Sentinel Row',360],['Totem Towers',380],['Vaulted Halls',400],
 ['Sun Dial Steps',360],['Relic Rush',390],['Ruin Gauntlet',410],['Sunset Citadel',440]
].map((n,li)=>mkLvl(4,li,n[0],n[1]))},
/* ============ WORLD 6 Â· SKY TEMPLE ============ */
{name:'Sky Temple',theme:'sky',lvls:[
 ['Cloud Hop',340],['Zephyr Steps',370],['Temple Gates',390],['Skyward Sprint',420],
 ['Windmill Walk',340],['Monsoon Run',360],['Thunder Terrace',380],['Cloudkeep',400],
 ['Levellands',360],['Storm Spire',390],['Sky Gauntlet',410],['Temple Citadel',440]
].map((n,li)=>mkLvl(5,li,n[0],n[1]))},
/* ============ WORLD 7 Â· EMBER KEEP ============ */
{name:'Ember Keep',theme:'lava',lvls:[
 ['Ashen Approach',340],['Magma Bridges',370],['Forge Climb',390],['Ember Gauntlet',420],
 ['Cinder Path',340],['Furnace Run',360],['Ash Tower',380],['Lava Ledger',400],
 ['Smokestep',360],['Molten March',390],['Ember Circle',410],['Keep Citadel',440]
].map((n,li)=>mkLvl(6,li,n[0],n[1]))},
/* ============ WORLD 8 Â· STARLIGHT SUMMIT ============ */
{name:'Starlight Summit',theme:'night',lvls:[
 ['Moonlit Path',340],['Aurora Ridge',370],['Night Ascent',390],['Starfall Finale',420],
 ['Comet Court',340],['Eclipse Run',360],['Meteor Mile',380],['Zenith Ridge',400],
 ['Stellar Steps',360],['Nova Dash',390],['Eternal Night',410],['Starlight Citadel',450]
].map((n,li)=>mkLvl(7,li,n[0],n[1]))}
];
/* ---------- build full 17-row maps & flatten ---------- */
function expand(def){
  const W=Math.max(def.w,...def.rows.map(r=>r.length));  // fit the widest row
  let ground=def.rows[def.rows.length-1]||'';   // entity row (stands on the ground)
  const sky=def.rows.slice(0,-1);
  while(sky.length>12){                          // drop empty filler rows first
    const idx=sky.findIndex(r=>/^\.+$/.test(r));
    sky.splice(idx<0?0:idx,1);
  }
  const rows=[];
  if(def.cave)rows.push(H(W),H(W));
  else rows.push(E(W/10),E(W/10));
  for(let i=0;i<12;i++){
    let r=sky[i]||'';
    if(r.length<W)r=r+'.'.repeat(W-r.length);
    rows.push(r.slice(0,W));
  }
  if(ground.length<W)ground=ground+'.'.repeat(W-ground.length);
  rows.push(ground.slice(0,W));                 // map row 14: entities
  let g=H(W).split('');                         // map rows 15-16: solid ground
  if(def.ice)for(const[st,len]of def.ice)for(let i=0;i<len&&st+i<W;i++)g[st+i]='I';
  if(def.pits)for(const[st,len]of def.pits)for(let i=0;i<len&&st+i<W;i++)g[st+i]='.';
  const gs=g.join('');
  rows.push(gs,gs);
  return rows;
}
/* ---------- builders: rooms, hardening, secrets, pipes ---------- */
function padRows(l){ // clamp to 13 content rows; index 12 = entity row (map row 14)
  const W=Math.max(l.w,...l.rows.map(r=>r.length));
  while(l.rows.length>13){ // drop all-blank rows first...
    const i=l.rows.findIndex(r=>/^\.+$/.test(r));
    if(i<0)break;
    l.rows.splice(i,1);
  }
  while(l.rows.length>13)l.rows.shift(); // ...then trim from the TOP (entity row stays last)
  while(l.rows.length<13)l.rows.unshift('.'.repeat(W)); // pad ABOVE so the entity row stays last
  l.rows=l.rows.slice(0,13);
  l.w=W;
}
function putR(rows,y,x,str){
  rows[y]=rows[y].slice(0,x)+str+rows[y].slice(x+str.length);
}
function makeRoom(def){
  const W=Math.max(def.w,...def.rows.map(r=>r.length));
  let g=H(W).split('');
  if(def.ice)for(const[st,len]of def.ice)for(let i=0;i<len&&st+i<W;i++)g[st+i]='I';
  if(def.pits)for(const[st,len]of def.pits)for(let i=0;i<len&&st+i<W;i++)g[st+i]='.';
  // never carve a pit under the spawn or the flag
  const ent=def.rows[12]||'';
  for(let x=0;x<W&&x<ent.length;x++){
    if(ent[x]==='P'||ent[x]==='F'||ent[x]==='C')g[x]='#';
  }
  const gs=g.join('');
  const rows=[];
  if(def.cave){rows.push(H(W),H(W));}else rows.push(E(W/10),E(W/10));
  for(let i=0;i<13;i++){
    const r=def.rows[i]||'';
    rows.push((r+'.'.repeat(W)).slice(0,W));
  }
  rows.push(gs,gs);
  return rows;
}
function harden(l,wi){
  const W=l.w,rows=l.rows;
  const groundSolid=x=>{
    for(const[st,len]of(l.pits||[]))if(x>=st&&x<st+len)return false;
    return true;
  };
  // 1. stepping stones across pits (map row 14 = rows[12])
  for(const[st,len]of(l.pits||[])){
    if(len>=4){
      putR(rows,12,st+1,'##');
      if(len>4)putR(rows,12,st+len-2,'##');
    }else if(len===3){
      putR(rows,12,st+1,'#');
    }
  }
  // 2. mystery box over a reachable ground tile (map row 12 = rows[10]).
  //    The box must never sit beside an elevated structure (pillar, tower
  //    platform, stair) — it would bonk-block the jump onto it and wall off
  //    the rest of the level.
  const nearPit=x=>{for(const[st,len]of(l.pits||[]))if(x>=st-2&&x<st+len+2)return true;return false;};
  const wallAt=x=>{const a=rows[10][x]||'.',b=rows[11][x]||'.';
    return a==='#'||a==='I'||a==='B'||b==='#'||b==='I'||b==='B';};
  const nearWall=c=>{for(let d=-3;d<=3;d++){const x=c+d;
    if(x>=0&&x<W&&wallAt(x))return true;}return false;};
  let cb=-1;
  for(let d=0;d<W;d++){
    const c=(Math.floor(W*0.5)+d)%W;
    const ent=rows[12][c];
    if(groundSolid(c)&&!nearPit(c)&&c>8&&c<W-10&&!nearWall(c)&&rows[10][c]==='.'&&rows[11][c]==='.'
      &&(ent==='.'||ent===undefined)){
      cb=c;break;
    }
  }
  if(cb<0){ // fallback: same, but only immediate sides must be clear
    for(let d=0;d<W;d++){
      const c=(Math.floor(W*0.5)+d)%W;
      if(groundSolid(c)&&c>8&&c<W-10&&!wallAt(c-1)&&!wallAt(c+1)&&rows[10][c]==='.'&&rows[11][c]==='.'){cb=c;break;}
    }
  }
  if(cb>=0)putR(rows,10,cb,'B');
  // 3. turrets (map row 14 = rows[12]), ramping with world —
  //    each one gets a 1-high step block nearby so it always guards
  //    reachable ground (and never floats unapproachable)
  const nT=wi>=6?3:wi>=4?2:wi>=1?1:0;
  const fracs=[0.30,0.55,0.78];
  const clear11=c2=>rows[11][c2]==='.';
  const tryTurret=c=>{
    if(!groundSolid(c)||c<=15||c>=W-16||rows[12][c]!=='.')return false;
    let hasGround=false;
    for(let d=-10;d<=10&&!hasGround;d++){const x=c+d;
      if(x>=0&&x<W&&rows[12][x]==='#'&&clear11(x))hasGround=true;}
    if(!hasGround){
      const cand=[c-3,c+3,c-4,c+4,c-5,c+5].find(x2=>x2>10&&x2<W-10&&groundSolid(x2)&&rows[12][x2]==='.'&&clear11(x2));
      if(cand===undefined)return false;
      putR(rows,12,cand,'#');
    }
    putR(rows,12,c,'X');placed++;return true;
  };
  let placed=0;
  for(let f=0;f<fracs.length&&placed<nT;f++)tryTurret(Math.floor(W*fracs[f]));
  // 4. pick a pipe column (map row 14) â€” generous clearance, late-map, solid ground
  const nearSpike=x=>{for(let dx=-2;dx<=2;dx++){const c=x+dx;if(c<0||c>=W)continue;
    if(rows[12][c]==='^'||rows[12][c]==='S')return true;}return false;};
  let pc=-1;
  const tryZone=(frac)=>{
    for(let d=0;d<W;d++){
      const c=(Math.floor(W*frac)+d)%W;
      if(!groundSolid(c)||nearPit(c)||nearSpike(c))continue;
      if(c<14||c>W-14)continue;
      if(rows[12][c]&&rows[12][c]!=='.')continue;
      // three clear rows above for the pipe body
      let clear=true;
      for(let r=9;r<=12;r++)if(rows[r]&&rows[r][c]!=='.')clear=false;
      if(!clear)continue;
      pc=c;return;
    }
  };
  tryZone(0.72);tryZone(0.6);tryZone(0.45);tryZone(0.3);
  if(pc<0)for(let c=14;c<W-14;c++){ // last resort: first clear column
    if(groundSolid(c)&&!nearPit(c)&&rows[12][c]==='.'&&rows[11][c]==='.'&&rows[10][c]==='.'){pc=c;break;}
  }
  l._pc=pc<0?Math.max(10,Math.min(W-10,14)):pc;
  // 5. walker patrol fix — no enemy may sit stuck against a wall. Measure the
  //    walker's patrol runway (solid ground continues, no wall/stone/spike/
  //    spring/turret in the way); if it can't patrol at least 4 tiles, move it
  //    to real open ground — or drop it entirely rather than leave it jittering.
  const blocked12=x=>{const c2=rows[12][x];
    return c2==='#'||c2==='I'||c2==='^'||c2==='S'||c2==='X'||c2==='T'||c2==='P'||c2==='C'||c2==='F'||c2==='W';};
  const P0=l._pc; // pipe column — the 'T' tile is stamped after this pass, block it here
  const passable12=x=>x>3&&x<W-4&&groundSolid(x)&&x!==P0&&x!==P0+1&&!blocked12(x);
  const runway=c=>{let l2=0,r2=0;
    for(let k=c-1;k>3&&passable12(k);k--)l2++;
    for(let k=c+1;k<W-4&&passable12(k);k++)r2++;
    return[l2,r2];};
  for(let x=4;x<W-4;x++){
    if(rows[12][x]!=='W')continue;
    const[l2,r2]=runway(x);
    // also relocate walkers camped right next to the pipe column — the player
    // warps back to P0+1 with zero invulnerability, so that tile must be clear
    if(groundSolid(x)&&Math.max(l2,r2)>=3&&Math.abs(x-P0)>2)continue;
    putS(rows,12,x,'.');
    let best=-1;
    for(let d=2;d<W-8&&best<0;d++){
      for(const c of[x-d,x+d]){
        if(c<=4||c>=W-4||!passable12(c))continue;
        if(Math.abs(c-(pc<0?l._pc:pc))<=3)continue;
        const[cl,cr]=runway(c);
        if(Math.max(cl,cr)>=4&&cl+cr>=6){best=c;break;}
      }
    }
    if(best>=0)putS(rows,12,best,'W');
  }
}
/* secret bonus room â€” a themed gauntlet rewarding coins/gem/box */
function secretDef(wi,li){
  const W=84;
  const rows=[];
  for(let i=0;i<13;i++)rows.push('.'.repeat(W));
  const S=putR.bind(null,rows);
  const pl=(wi+li)%2?[14,4,30,4,46,5,60,4]:[12,4,26,4,40,5,56,4];
  const pits=[];
  for(let i=0;i<pl.length;i+=2)pits.push([pl[i],pl[i+1]]);
  const groundSolid=x=>{
    for(const[st,len]of pits)if(x>=st&&x<st+len)return false;
    return true;
  };
  S(12,2,'P'); // spawn
  for(const[st,len]of pits){
    S(12,st+1,'##');
    if(len>4)S(12,st+len-2,'##');
  }
  S(3,8,'oooooooo');
  S(5,20,'oooo');
  S(7,30,'oooo');
  if(wi>=4){S(4,50,'oooo');S(6,64,'ooooo');}
  S(11,36,'##');S(8,36,'G');  // high gem platform
  S(10,52,'B');               // mystery box (3 above ground â€” bonkable)
  const nT=wi>=5?2:1;
  const tc=[24,44,64];
  for(let i=0;i<nT;i++){
    if(groundSolid(tc[i])&&rows[12][tc[i]]==='.')S(12,tc[i],'X');
  }
  S(10,70,'oooo');
  return{w:W,rows,pits,cave:false};
}
function stamp(map,tx,ty,ch){
  map[ty]=map[ty].slice(0,tx)+ch+map[ty].slice(tx+1);
}
const LEVELS=[];
WORLDS.forEach((wd,wi)=>wd.lvls.forEach((l,li)=>{
  padRows(l);
  harden(l,wi);
  const mainDef={w:l.w,cave:l.cave,rows:l.rows,ice:l.ice,pits:l.pits};
  const secDef=secretDef(wi,li,l.w);
  const main=makeRoom(mainDef);
  const sec=makeRoom(secDef);
  const pc=l._pc;
  stamp(main,pc,14,'T');              // main entry pipe (press â–¼ while inside)
  const sx=secDef.w-8;
  stamp(sec,sx,14,'T');               // secret exit pipe
  const pipes=[
    {from:{r:0,tx:pc,ty:14},to:{r:1,tx:3,ty:15}},
    {from:{r:1,tx:sx,ty:14},to:{r:0,tx:pc+1,ty:15}}
  ];
  LEVELS.push({name:l.name,world:wi,index:li,w:l.w,maps:[main,sec],pipes,secretCol:sx});
}));

